title: WALLSIN.se Entreprenad i Torslanda och Göteborg
author:
  name: Joachim Wallsin
  email: 'joachim@wallsin.com'
metadata:
    description: 'WALLSIN.se Entreprenad utför alla sorters markarbeten. Vi har en stor maskinpark med diverse grävmaskiner, traktorer och minigrävare.'
    keywords: 'conny wallsin, conny, wallsin, roy wallsin, roy, entreprenad, traktorgrävare, wallsin entreprenad, grävtjänst, grävmaskin, traktor, torslanda, göteborg, mark, grund, beläggning, markarbete, grundarbete, beläggningsarbet'
google_analytics_id: 'UA-15251055-1'
