absolute_urls: false

home:
  alias: '/hem'
  hide_in_urls: false

languages:
  supported:
    - sv
  include_default_lang: false
  pages_fallback_only: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false

pages:
  theme: wallsin
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: true

debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
gpm:
  releases: stable
  verify_peer: true

strict_mode:
  yaml_compat: true
  twig_compat: true
  blueprint_compat: true